POST http://localhost:3003/api/projects/6593c6e7a27bdd9a5a8fcba9/issues
Content-Type: application/json
Authorization:
{
  "title": "Lược bớt thông tin",
  "description": "Card visit đang có quá nhiều thông tin, gẫy nhiễu và chữ rất nhỏ. Cần chọn lọc những thông tin cần thiết nhất để giữ lại."
}