GET http://localhost:3003/api/projects/659bcbab51659ac5c226fb12/issues/659bcc1d51659ac5c226fb2d/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBoaWhkIiwiaWQiOiI2NTliOTRmNmI3OTJjNDM1MWU4ZWI3M2QiLCJpYXQiOjE3MTIwMzEyMDYsImV4cCI6MTcxMjAzNDgwNn0.aOG1Cfpz3QQJU1_f02gQ2GRrN8wp4bbyuwVs1TJmzUw